# Generated by Django 4.2 on 2026-01-02 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('applied_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('rejected', 'Rejected'), ('passed', 'Passed')], default='new', max_length=20)),
                ('employer_note', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_score', models.FloatField(blank=True, null=True)),
                ('skill_score', models.FloatField(blank=True, null=True)),
                ('req_score', models.FloatField(blank=True, null=True)),
                ('match_level', models.CharField(blank=True, max_length=50, null=True)),
                ('manual_rank', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'applications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('end_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('requirements', models.CharField(blank=True, max_length=255, null=True)),
                ('skills', models.CharField(blank=True, max_length=255, null=True)),
                ('benefit', models.CharField(blank=True, max_length=255, null=True)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'jobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('password_hash', models.CharField(max_length=100)),
                ('role', models.BooleanField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('sex', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cvs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='cv_files/')),
                ('file_name', models.CharField(max_length=255)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
            options={
                'db_table': 'cvs',
            },
        ),
    ]
