# Generated by Django 4.2 on 2025-12-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cvs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_id', models.IntegerField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('extract_text', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cvs',
                'managed': False,
            },
        ),
    ]
