# Generated by Django 4.2 on 2025-12-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('employer_note', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_score', models.IntegerField(blank=True, max_length=255, null=True)),
                ('manual_rank', models.IntegerField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'applications',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cvs',
            options={},
        ),
    ]
