# Generated by Django 4.2 on 2025-12-22 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_application_alter_cvs_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvs',
            old_name='extract_text',
            new_name='extracted_text',
        ),
        migrations.RemoveField(
            model_name='cvs',
            name='candidate_id',
        ),
        migrations.RemoveField(
            model_name='cvs',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='cvs',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='cvs',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='cv_files/'),
        ),
        migrations.AddField(
            model_name='cvs',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cvs',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.users'),
        ),
        migrations.AlterField(
            model_name='cvs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='cvs',
            table=None,
        ),
    ]
