# Generated by Django 4.2 on 2025-12-22 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_extract_text_cvs_extracted_text_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cvs',
            table='cvs',
        ),
    ]
