# Generated by Django 4.2 on 2025-12-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_cvs_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('applied_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('rejected', 'Rejected'), ('passed', 'Passed')], default='new', max_length=20)),
                ('employer_note', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_score', models.CharField(blank=True, max_length=255, null=True)),
                ('manual_rank', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'applications',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.AlterField(
            model_name='cvs',
            name='uploaded_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
